import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        coal: "#061014",
        ink: "#08171A",
        ash: "#0B1B1F",
        bone: "#F1E4CC",
        parchment: "#E8D8C0",
        brass: "#A16428",
        copper: "#7A4A21",
        blood: "#7A1F1F",
        bottle: "#4F6B3A",
        gabinete: {
          exterior: "#0B0D17",
          exterior2: "#121626",
          exterior3: "#151A2C",
          panel: "rgba(15, 20, 35, 0.75)",
          panelSolid: "#121626",
          paper: "#F2EFE9",
          paper2: "#A3A09B",
          paper3: "#7F7A72",
          paperLight: "#F2EFE9",
          text: "#F2EFE9",
          muted: "#A3A09B",
          faint: "#7F7A72",
          darkBrown: "#F2EFE9",
          brown: "#C5A059",
          copper: "#8A6E35",
          gold: "#E6C987",
          oldGold: "#C5A059",
          line: "#C5A059",
          lineLight: "#E6C987",
          lineDark: "#8A6E35",
          error: "#7A1F1F",
          available: "#4F6B3A",
          consult: "#9A6A1F",
        },
      },
      fontFamily: {
        display: ["Playfair Display", "Cormorant Garamond", "Georgia", "serif"],
        serifDisplay: ["Playfair Display", "Cormorant Garamond", "Georgia", "serif"],
        editorial: ["Playfair Display", "Lora", "Georgia", "serif"],
        body: ["Montserrat", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      boxShadow: {
        cabinet: "0 40px 100px rgba(0,0,0,.55)",
        relic: "0 14px 34px rgba(74,45,22,.18)",
        paper: "0 16px 46px rgba(74,45,22,.16)",
      },
      borderRadius: {
        object: "10px",
      },
    },
  },
  plugins: [],
} satisfies Config;
